"""G-code footer parser for scripts/slice_metrics.py. No slicer needed."""

import importlib.util
import sys
from pathlib import Path

spec = importlib.util.spec_from_file_location(
    "slice_metrics",
    Path(__file__).resolve().parents[1] / "scripts" / "slice_metrics.py",
)
sm = importlib.util.module_from_spec(spec)
sys.modules["slice_metrics"] = sm
spec.loader.exec_module(sm)

GCODE = """; generated by PrusaSlicer 2.9.4
;LAYER_CHANGE
;Z:0.2
G1 X1 Y1 E0.1
;LAYER_CHANGE
;Z:0.4
G1 X2 Y2 E0.1
;LAYER_CHANGE
;Z:73.4
; filament used [mm] = 37539.67
; filament used [cm3] = 90.29
; filament used [g] = 111.96
; total filament used [g] = 111.96
; estimated printing time (normal mode) = 1d 6h 22m 5s
; estimated printing time (silent mode) = 6h 25m 42s
; estimated first layer printing time (normal mode) = 9m 9s
; layer_height = 0.2
"""


def test_parse_duration_h():
    assert sm.parse_duration_h("6h 22m 5s") == 6 + 22 / 60 + 5 / 3600
    assert sm.parse_duration_h("1d 2h") == 26.0
    assert sm.parse_duration_h("45s") == 45 / 3600


def test_parse_gcode(tmp_path):
    p = tmp_path / "x.gcode"
    p.write_text(GCODE)
    r = sm.parse_gcode(p)
    assert r["layers"] == 3
    assert r["max_z_mm"] == 73.4
    assert r["filament_g"] == 111.96
    assert r["filament_cm3"] == 90.29
    assert r["filament_mm"] == 37539.67
    assert abs(r["time_h"] - (24 + 6 + 22 / 60 + 5 / 3600)) < 1e-3
    assert r["time_text"] == "1d 6h 22m 5s"
    assert abs(r["first_layer_h"] - (9 / 60 + 9 / 3600)) < 1e-6


def test_parse_info():
    info = sm.parse_info(
        "[B3.stl]\nsize_x = 330.0\nnumber_of_facets = 220220\nmanifold = yes\nvolume = 163203.875\n"
    )
    assert info == {
        "size_x": 330.0,
        "number_of_facets": 220220,
        "manifold": True,
        "volume": 163203.875,
    }
    assert sm.parse_info("manifold = no\n")["manifold"] is False


def test_warnings_filter_progress():
    out = "10 => Processing triangulated mesh\nWarning: model is not manifold\nSlicing result exported to x\n"
    assert sm.warnings_from(out) == ["Warning: model is not manifold"]
