"""Design your own diverging colormap - the knobs, demonstrated.

A static gallery of the OKLab palette knobs (the interactive version is
`loopviz palette <candidate>`). Each palette is generated by
loopviz.palette from six knobs; interpolation is in OKLab so lightness
and chroma behave perceptually, then gamut-clipped to sRGB.

Run: .venv/bin/python scripts/exp_custom_diverging.py
       [--candidate songop_t002_f3998_n1322_c99.3]
"""

import argparse
import sys
from pathlib import Path

import numpy as np
from PIL import Image

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from loopviz.palette import PaletteSpec, apply_spec, gamut_report
from loopviz.sheet import make_sheet

ROOT = Path(__file__).parent.parent
OUT = ROOT / "runs" / "exp_custom_diverging"
Image.MAX_IMAGE_PIXELS = None


# The six-knob design space, walked to show what each knob does.
DEMO = [
    PaletteSpec("ember (dark field, blue/orange)", hue_neg=250, hue_pos=55,
                L_center=0.13, L_end=0.85, C_end=0.11),
    PaletteSpec("drifted arms (+40 deg hue rotation)", hue_neg=250, hue_pos=55,
                L_center=0.13, L_end=0.85, C_end=0.11, drift=40),
    PaletteSpec("muted (half chroma)", hue_neg=250, hue_pos=55, L_center=0.13,
                L_end=0.85, C_end=0.055),
    PaletteSpec("paper (light field)", hue_neg=250, hue_pos=55, L_center=0.97,
                L_end=0.35, C_end=0.10),
    PaletteSpec("wine-moss (analogous, mid-gray field)", hue_neg=10,
                hue_pos=140, L_center=0.55, L_end=0.25, C_end=0.09),
    PaletteSpec("riso duotone (saturated - see gamut note)", hue_neg=330,
                hue_pos=200, L_center=0.98, L_end=0.55, C_end=0.17),
]


def _default_candidate() -> str:
    """First available song-operator candidate, so the no-arg run just works."""
    hits = sorted((ROOT / "runs").glob("songop_*/presentation.png"))
    if not hits:
        raise SystemExit("no songop_* candidates in runs/ - pass --candidate")
    return hits[0].parent.name


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--candidate", default=None,
                    help="candidate id (default: first songop_* in runs/)")
    args = ap.parse_args()
    OUT.mkdir(parents=True, exist_ok=True)
    candidate = args.candidate or _default_candidate()

    g = np.asarray(Image.open(ROOT / "runs" / candidate /
                              "presentation.png").convert("L"),
                   dtype=np.float64) / 255.0

    tiles, notes = [], []
    for spec in DEMO:
        rep = gamut_report(spec)
        tag = "printable" if rep["printable"] else "OUT OF GAMUT"
        tiles.append((f"{spec.name} [{tag}]", apply_spec(g, spec)))
        notes.append(f"- {spec.name}: {tag}, "
                     f"max OKLab chroma {rep['max_oklab_chroma']:.3f} "
                     f"({rep['method']})")

    make_sheet(tiles, OUT / "custom_diverging.png", tile_size=430, cols=3,
               readme="# exp_custom_diverging: designing diverging palettes "
               "in OKLab\n\n"
               f"Candidate: {candidate}. Six knobs per palette (hue_neg, "
               "hue_pos, L_center, L_end, C_end, drift); interpolation in "
               "OKLab, gamut-clipped to sRGB. The center color owns ~95% of "
               "the print (most entries near zero), so choose the field "
               "first, accents second.\n\nPrint gamut (coated CMYK if an ICC "
               "profile is found, else conservative chroma ceiling):\n\n"
               + "\n".join(notes) + "\n\nThe saturated riso duotone is meant "
               "for spot-ink risograph, not CMYK, so it flags out of gamut "
               "here - that is the check working, not a bug.\n")
    print(f"wrote {OUT}/custom_diverging.png ({len(tiles)} tiles)")


if __name__ == "__main__":
    main()
